# -------------------------------------------------------------------------------------
#
#    Config file for gene expression in dev human brain study
#
# -------------------------------------------------------------------------------------

__default__:
    num_cores: 1
    total_mem: 10G
    duration: 0-05:00:00

# ---------  CELL RANGER  ----------
CR_cnt_RNA:
    num_cores: 32
    total_mem: 256G

CR_cnt_ATAC:
    num_cores: 32
    total_mem: 143G
    duration: 1-00:00:00

CR_aggr_ATAC:
    num_cores: 32
    total_mem: 143G
    duration: 1-00:00:00


# ----------  ARCHR  ---------------
snATAC_seq_QC:
    num_cores: 32
    total_mem: 128G
snATAC_seq_cluster_QC:
    num_cores: 12
    total_mem: 96G
snATAC_seq_QC_LSI_params:
    num_cores: 32
    total_mem: 128G
snATAC_remove_batch_effects:
    num_cores: 12
    total_mem: 96G
snATAC_unconstrained_integration:
    num_cores: 12
    total_mem: 96G
snATAC_constrained_integration:
    num_cores: 12
    total_mem: 96G
snATAC_pseudo_bulk_reps_and_peak_calling:
    num_cores: 12
    total_mem: 96G
snATACseq_call_peaks_ext_500bp:
    num_cores: 12
    total_mem: 96G
snATAC_additional_analyses:
    num_cores: 12
    total_mem: 96G
snATACseq_SVM_prep:
    num_cores: 2
    total_mem: 40G

# -----------  LDSR  ---------------
make_annot:
    num_cores: 1
    maxvmem: 10G
ldsr:
    num_cores: 1
    maxvmem: 10G
partitioned_heritability:
    num_cores: 1
    maxvmem: 20G
partitioned_heritability_conditional_fc_ExN:
    num_cores: 1
    maxvmem: 20G
partitioned_heritability_conditional_fc_RG:
    num_cores: 1
    maxvmem: 20G 
partitioned_heritability_conditional_ge_RG:
    num_cores: 1
    maxvmem: 20G 


# -------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------
